version: "3.8"
services:
  config-server:
    image: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend

  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  gateway:
    ports:
      - "8080:8080"
    image: ../../backend/gateway-service
    depends_on:
      - config-server
      - eureka-server
    networks:
      - backend

networks:
  backend: