version: '3.8'

services:
  config-server:
    image: config-server
    build:
      context: ../config-server
    ports:
      - "8888:8888"
    env_file:
      - ../config-server/.env

  eureka-server:
    image: eureka-server
    build:
      context: ../eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

networks:
  default:
  backend: