server:
  port: 8082

spring:
  application:
    name: user-service # 이 이름으로 유레카에 서비스 등록 후 로드밸런싱

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true