spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${USER_DB_NAME}
    username: ${USER_DB_USER}
    password: ${USER_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  cloud:
    config:
      uri: http://config-server:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info